# Generated by Django 5.0.4 on 2024-04-27 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(max_length=100)),
                ('Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.TextField()),
                ('Licence', models.FileField(blank=True, null=True, upload_to='DeliveryBoy')),
                ('AdharCard', models.FileField(blank=True, null=True, upload_to='DeliveryBoy')),
                ('PanCard', models.FileField(blank=True, null=True, upload_to='DeliveryBoy')),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('PassWord', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpanseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('Expanse', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('PartyName', models.CharField(max_length=100)),
                ('Number', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.TextField()),
                ('GSTNo', models.CharField(max_length=100)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('TypeofPurchase', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(max_length=100)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Tax', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=100)),
                ('MinQty', models.CharField(blank=True, max_length=100)),
                ('MaxQty', models.CharField(blank=True, max_length=100)),
                ('BarcodeNo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
