# Generated by Django 5.0.4 on 2024-04-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partymodel',
            name='TypeofPurchase',
        ),
        migrations.AddField(
            model_name='partymodel',
            name='Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
