# Generated by Django 5.0.4 on 2024-04-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_partymodel_typeofpurchase_partymodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiilNoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillNo', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Tax', models.CharField(blank=True, max_length=100, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('PurchasePrice', models.CharField(blank=True, max_length=100, null=True)),
                ('PurchaseIncTax', models.CharField(blank=True, max_length=100, null=True)),
                ('MRP', models.CharField(blank=True, max_length=100, null=True)),
                ('MinQty', models.CharField(blank=True, max_length=100)),
                ('MaxQty', models.CharField(blank=True, max_length=100)),
                ('BarcodeNo', models.CharField(blank=True, max_length=100)),
                ('Quantity', models.CharField(blank=True, max_length=100)),
                ('Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('sid', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
