# Generated by Django 5.0.4 on 2024-04-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_biilnomodel_nmmodel_stockmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmodel',
            name='MRP',
        ),
    ]
