# Generated by Django 5.0.4 on 2024-04-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_stockmodel_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='HSNCode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
