# Generated by Django 5.0.4 on 2024-04-29 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_purchaseentrymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OldProductId', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductId', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Tax', models.CharField(blank=True, max_length=100, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('PurchasePrice', models.CharField(blank=True, max_length=100, null=True)),
                ('PurchaseIncTax', models.CharField(blank=True, max_length=100, null=True)),
                ('MinQty', models.CharField(blank=True, max_length=100)),
                ('MaxQty', models.CharField(blank=True, max_length=100)),
                ('BarcodeNo', models.CharField(blank=True, max_length=100)),
                ('Quantity', models.CharField(blank=True, max_length=100)),
                ('Amount', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 19, 51, 51, 546088)),
        ),
    ]
