# Generated by Django 5.0.4 on 2024-04-29 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_mainstockmodel_alter_purchaseentrymodel_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 21, 35, 51, 65629)),
        ),
    ]
