# Generated by Django 5.0.4 on 2024-04-30 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_purchaseentrymodel_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentrymodel',
            name='DueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseentrymodel',
            name='ExpiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 56, 46, 743929)),
        ),
    ]
