# Generated by Django 5.0.4 on 2024-04-30 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_purchaseentrymodel_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 10, 56, 59, 925831)),
        ),
    ]
