# Generated by Django 5.0.4 on 2024-04-30 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_purchaseentrymodel_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Tax', models.CharField(blank=True, max_length=100, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('PurchaseIncTax', models.CharField(blank=True, max_length=100, null=True)),
                ('BarcodeNo', models.CharField(blank=True, max_length=100)),
                ('Quantity', models.CharField(blank=True, max_length=100)),
                ('Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('sid', models.CharField(blank=True, max_length=100, null=True)),
                ('ProfitMargin', models.CharField(blank=True, max_length=100, null=True)),
                ('BasicSalesPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('Discount', models.CharField(blank=True, max_length=100, null=True)),
                ('SalesPriceAfterDiscount', models.CharField(blank=True, max_length=100, null=True)),
                ('IncSalesPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('TotalSales', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseentrymodel',
            name='TPurchaseIncTax',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseentrymodel',
            name='TPurchasePrice',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseentrymodel',
            name='TQuantity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 12, 2, 53, 955836)),
        ),
    ]
