# Generated by Django 5.0.4 on 2024-04-30 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_salesstockmodel_purchaseentrymodel_tpurchaseinctax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 12, 12, 26, 809655)),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='TPurchaseIncTax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='TPurchasePrice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='TQuantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
