# Generated by Django 5.0.4 on 2024-04-30 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_salesentrymodel_alter_purchaseentrymodel_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 17, 51, 3, 979303)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 17, 51, 3, 989304)),
        ),
    ]
