# Generated by Django 5.0.4 on 2024-05-03 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_purchaseentrymodel_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseentrymodel',
            name='ExpiryDate',
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 7, 11, 46, 593737)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 7, 11, 46, 603733)),
        ),
    ]
