# Generated by Django 5.0.4 on 2024-05-03 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_purchaseentrymodel_expirydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 12, 46, 45, 980277)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 12, 46, 45, 990285)),
        ),
    ]
