# Generated by Django 5.0.4 on 2024-05-05 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_purchaseentrymodel_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='ExpiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='MFGDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 13, 25, 16, 567617)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 13, 25, 16, 567617)),
        ),
    ]
