# Generated by Django 5.0.4 on 2024-05-05 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_productmodel_expirydate_productmodel_mfgdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expansemodel',
            old_name='Amount',
            new_name='Type',
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 13, 43, 2, 436173)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 13, 43, 2, 451927)),
        ),
    ]
