# Generated by Django 5.0.4 on 2024-05-05 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_amount_expansemodel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentrymodel',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesentrymodel',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 14, 47, 26, 588271)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 14, 47, 26, 588271)),
        ),
    ]
