# Generated by Django 5.0.4 on 2024-05-08 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_chargeslistmodel_alter_expanseentrymodel_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentrymodel',
            name='TChargesAmount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesentrymodel',
            name='TChargesAmount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expanseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 40, 39, 656725)),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 40, 39, 656725)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 11, 40, 39, 656725)),
        ),
    ]
