# Generated by Django 5.0.4 on 2024-05-08 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_purchaseentrymodel_tchargesamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeslistmodel',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expanseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 13, 13, 3, 753019)),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 13, 13, 3, 737369)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 13, 13, 3, 753019)),
        ),
    ]
