# Generated by Django 5.0.4 on 2024-05-17 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_expanseentrymodel_terms_purchaseentrymodel_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesentrymodel',
            name='TypeofPayment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expanseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 14, 45, 3, 498109)),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 14, 45, 3, 488129)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 14, 45, 3, 498109)),
        ),
    ]
