# Generated by Django 5.0.4 on 2024-05-22 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_expanseentrymodel_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditSalesStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Tax', models.CharField(blank=True, max_length=100, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('PurchaseIncTax', models.CharField(blank=True, max_length=100, null=True)),
                ('BarcodeNo', models.CharField(blank=True, max_length=100)),
                ('Quantity', models.CharField(blank=True, max_length=100)),
                ('Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('sid', models.CharField(blank=True, max_length=100, null=True)),
                ('ProfitMargin', models.CharField(blank=True, max_length=100, null=True)),
                ('BasicSalesPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('Discount', models.CharField(blank=True, max_length=100, null=True)),
                ('SalesPriceAfterDiscount', models.CharField(blank=True, max_length=100, null=True)),
                ('IncSalesPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('TotalSales', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expanseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 13, 23, 4, 858488)),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 13, 23, 4, 848489)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 13, 23, 4, 858488)),
        ),
    ]
