# Generated by Django 5.0.4 on 2024-05-24 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_editsalesstockmodel_alter_expanseentrymodel_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expanseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 9, 7, 45, 271973)),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 9, 7, 45, 251972)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 9, 7, 45, 261970)),
        ),
    ]
