# Generated by Django 5.0.4 on 2024-06-01 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_purchaseentrymodel_status_alter_amountmodel_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expanseentrymodel',
            name='PayableAmount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expanseentrymodel',
            name='status',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='amountmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 8, 59, 17, 378661)),
        ),
        migrations.AlterField(
            model_name='expanseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 8, 59, 17, 374661)),
        ),
        migrations.AlterField(
            model_name='ledgerreportmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 8, 59, 17, 381660)),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 8, 59, 17, 361662)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 8, 59, 17, 370661)),
        ),
        migrations.AlterField(
            model_name='useramountmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 8, 59, 17, 380660)),
        ),
    ]
