# Generated by Django 5.0.4 on 2024-06-01 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_amountmodel_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 11, 39, 7, 666698)),
        ),
        migrations.AlterField(
            model_name='expanseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 11, 39, 7, 661698)),
        ),
        migrations.AlterField(
            model_name='ledgerreportmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 11, 39, 7, 668698)),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 11, 39, 7, 649698)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 11, 39, 7, 658698)),
        ),
        migrations.AlterField(
            model_name='useramountmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 11, 39, 7, 667698)),
        ),
    ]
