# Generated by Django 5.0.4 on 2024-06-10 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_pendingamountmodel_pendingamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='AdharCard',
            field=models.FileField(blank=True, null=True, upload_to='DeliveryBoy'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='PanCard',
            field=models.FileField(blank=True, null=True, upload_to='DeliveryBoy'),
        ),
        migrations.AlterField(
            model_name='amountmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 17, 50, 40, 470491)),
        ),
        migrations.AlterField(
            model_name='expanseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 17, 50, 40, 470491)),
        ),
        migrations.AlterField(
            model_name='ledgerreportmodel',
            name='LRDate',
            field=models.DateField(default=datetime.date(2024, 6, 10)),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 17, 50, 40, 454882)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 17, 50, 40, 470491)),
        ),
        migrations.AlterField(
            model_name='useramountmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 17, 50, 40, 470491)),
        ),
    ]
