# Generated by Django 5.0.4 on 2024-06-10 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_userdetails_adharcard_userdetails_pancard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 17, 51, 28, 560733)),
        ),
        migrations.AlterField(
            model_name='expanseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 17, 51, 28, 545111)),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 17, 51, 28, 545111)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 17, 51, 28, 545111)),
        ),
        migrations.AlterField(
            model_name='useramountmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 17, 51, 28, 560733)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='AdharCard',
            field=models.FileField(blank=True, null=True, upload_to='User'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='PanCard',
            field=models.FileField(blank=True, null=True, upload_to='User'),
        ),
    ]
