# Generated by Django 5.0.4 on 2024-06-12 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_salesentrymodel_billclear_alter_amountmodel_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 23, 12, 40, 88793)),
        ),
        migrations.AlterField(
            model_name='expanseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 23, 12, 40, 73022)),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='ExpiryDate',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='MFGDate',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 23, 12, 40, 73022)),
        ),
        migrations.AlterField(
            model_name='salesentrymodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 23, 12, 40, 73022)),
        ),
        migrations.AlterField(
            model_name='useramountmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 23, 12, 40, 88793)),
        ),
    ]
